version: "3"

services:

  website:
    container_name: website
    image: website
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: always
    ports:
      - 0.0.0.0:80:3000
      - 0.0.0.0:443:3001
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./www.abelromero.com/:/opt/www.abelromero.com
